"""Bounded JSONL client for the real `aelix --mode rpc` CLI."""

from __future__ import annotations

import asyncio
import contextlib
import hashlib
import json
import logging
import os
import re
import signal
import subprocess
import time
import uuid
from collections.abc import Iterator
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .config import Config
from .storage import private_directory, write_text

log = logging.getLogger(__name__)

_CHUNK = 64 * 1024
_EDGE = 4096  # bytes kept from both ends of an oversized line
_STDERR_KEEP = 16 * 1024
_STDERR_TAIL = 8 * 1024
_FAILED = frozenset({"error", "aborted"})
_TOOL_USE = frozenset({"toolUse", "tool_use"})
# Responses put "type" first (rpc_types); events are dataclass-serialised, so "type" is last.
_RESPONSE = re.compile(rb'\s*\{\s*"type"\s*:\s*"response"')
_RESPONSE_ID = re.compile(rb'"id"\s*:\s*"([0-9A-Za-z_\-]{1,128})"')
_EVENT = re.compile(rb'"type"\s*:\s*"([0-9A-Za-z_]{1,64})"\s*\}\s*$')
_ROLE = re.compile(rb'"role"\s*:\s*"([0-9A-Za-z_]{1,32})"\s*\}\s*,\s*"type"\s*:\s*"message_end"\s*\}\s*$')
# message_update ends with its assistant_message_event, whose own "type" is its last key.
_DELTA = re.compile(rb'"type"\s*:\s*"([0-9A-Za-z_]{1,64})"\s*\}\s*,\s*"type"\s*:\s*"message_update"\s*\}\s*$')
_PROGRESS = frozenset({"tool_execution_start", "tool_execution_end", "auto_retry_start", "auto_retry_end",
                       "compaction_start", "compaction_end", "message_update"})
_SECRET = re.compile(
    r"(?P<bearer>\b(?i:bearer)\s+)[^\s\"',;]+"
    r"|\b(?:sk|pk|rk)-[A-Za-z0-9_\-]{8,}|\bxox[a-z]-[A-Za-z0-9\-]{8,}"
    r"|\b(?:gh[pousr]|github_pat)_[A-Za-z0-9_]{8,}|\bglpat-[A-Za-z0-9_\-]{8,}"
    r"|(?P<run>[A-Za-z0-9+/_\-]{32,}=*)"
)


_SHIM = '''"""Generated by aelix-mattermost: loads the installed extension {reference!r} by name."""

import importlib
import os
import sys


def setup(aelix):
    # Never import from the working directory, where tools can write.
    cwd = os.path.realpath(os.getcwd())
    sys.path[:] = [p for p in sys.path if p not in ("", ".") and os.path.realpath(p) != cwd]
    return getattr(importlib.import_module({module!r}), {attribute!r})(aelix)
'''


class RpcError(RuntimeError):
    pass


class RpcTimeout(RpcError):
    pass


class NothingToCompact(RpcError):
    """Aelix keeps the recent part of a conversation as is; a short one has nothing to compact."""


class RpcRunFailed(RpcError):
    """Aelix finished the prompt without an answer; the idle child stays usable.

    `answers` holds the answers Aelix completed before the failure (see Turn)."""

    def __init__(self, message: str, answers: list[tuple[int, str]] | None = None) -> None:
        super().__init__(message)
        self.answers = answers or []


@dataclass
class Turn:
    """The answers of one prompt and the steering messages merged into its run.

    Each answer is (request index, text): 0 is the prompt, n the n-th steered message.
    Aelix answers a steered message after it finishes the turn it was injected into, so
    a turn that completed an answer before the injection gives the earlier request its own
    answer; the last answer belongs to the newest request Aelix took in."""

    answers: list[tuple[int, str]]

    @property
    def text(self) -> str:
        return self.answers[-1][1] if self.answers else ""


@dataclass
class Activity:
    """What the running prompt is doing, for progress display."""

    phase: str = "starting"  # starting, thinking, writing, tool, retrying, compacting
    tool: str = ""
    tools_used: int = 0
    started: float = field(default_factory=time.monotonic)
    partial: str = ""  # the latest partial answer text (only when tracked)


@dataclass
class _Steer:
    text: str
    images: list[dict] | None
    state: str = "sending"  # sending, queued, taken, failed


def _group(pattern: re.Pattern[bytes], data: bytes) -> str | None:
    match = pattern.search(data)
    return match.group(1).decode() if match else None


def _load(line: bytearray | None) -> dict | None:
    if line is None:
        return None
    try:
        value = json.loads(line)
    except (ValueError, RecursionError):
        return None
    return value if isinstance(value, dict) else None


def _data(command: str, response: dict) -> dict:
    if response.get("success") is not True:
        raise RpcError(f"Aelix rejected RPC command {command}")
    data = response.get("data", {})
    if not isinstance(data, dict):
        raise RpcError("Aelix returned invalid RPC data")
    return data


def _outcome(message: dict) -> tuple[str | None, str]:
    """(stop_reason, text) of an assistant message as Aelix serialises it."""
    reason = message.get("stop_reason", message.get("stopReason"))
    content = message.get("content")
    text = "".join(x["text"] for x in content if isinstance(x, dict) and x.get("type") == "text"
                   and isinstance(x.get("text"), str)) if isinstance(content, list) else ""
    return (reason if isinstance(reason, str) else None), text


def _hide(match: re.Match[str]) -> str:
    if match.group("bearer"):
        return match.group("bearer") + "[redacted]"
    run = match.group("run")
    if run and (not any(c.isdigit() for c in run) or run.count("/") > 3):
        return run  # words and file paths stay readable
    return "[redacted]"


def _redact(text: str, token: str = "") -> str:
    """Mask credentials that provider errors and tracebacks may print."""
    if len(token) >= 8:  # a short placeholder would mask ordinary letters
        text = text.replace(token, "[redacted]")
    return _SECRET.sub(_hide, text)


def _killpg(pid: int, number: int) -> None:
    with contextlib.suppress(ProcessLookupError, PermissionError):
        os.killpg(pid, number)


async def _exited(process: asyncio.subprocess.Process, seconds: float) -> bool:
    """Poll returncode: wait() also waits for pipes that a descendant may hold open."""
    loop = asyncio.get_running_loop()
    deadline = loop.time() + seconds
    while process.returncode is None and loop.time() < deadline:
        await asyncio.sleep(0.05)
    return process.returncode is not None


class _Lines:
    """LF-only framing with a per-line cap; oversized lines keep only their edges."""

    def __init__(self, limit: int) -> None:
        self.limit = limit
        self.buffer = bytearray()
        self.head = self.tail = b""
        self.dropping = False

    def feed(self, chunk: bytes) -> Iterator[tuple[bytearray | None, bytes, bytes]]:
        start = 0
        while (end := chunk.find(b"\n", start)) >= 0:
            self._add(chunk[start:end])
            yield self._take()
            start = end + 1
        self._add(chunk[start:])

    def _add(self, piece: bytes) -> None:
        if self.dropping:
            self.tail = (self.tail + piece)[-_EDGE:]
        elif len(self.buffer) + len(piece) > self.limit:
            self.head = bytes(self.buffer[:_EDGE]) + piece[:max(0, _EDGE - len(self.buffer))]
            self.tail = (bytes(self.buffer[-_EDGE:]) + piece)[-_EDGE:]
            self.buffer, self.dropping = bytearray(), True
        else:
            self.buffer += piece

    def _take(self) -> tuple[bytearray | None, bytes, bytes]:
        if self.dropping:
            result = None, self.head, self.tail
            self.head = self.tail = b""
            self.dropping = False
            return result
        line, self.buffer = self.buffer, bytearray()
        return line, bytes(line[:_EDGE]), bytes(line[-_EDGE:])


class RpcProcess:
    max_line = 64 * 1024 * 1024  # longer lines are dropped; their event type still counts
    start_grace = 2.0  # an accepted prompt starts a run (or keeps streaming) by then
    poll_interval = 0.2  # get_state cadence while Aelix retries, recovers or compacts
    abort_grace = 2.0  # abort RPC plus idle wait before the child is signalled
    term_grace = 5.0  # SIGTERM (CTRL_BREAK on Windows) before SIGKILL
    probe_timeout = 2.0  # get_state of idle()

    def __init__(self, config: Config, work_dir: Path, session_dir: Path,
                 context_file: Path, session_file: Path | None = None, *,
                 tools: tuple[str, ...] | None = None, model: str | None = None,
                 prompt_file: Path | None = None, track_partial: bool = False) -> None:
        self.config = config
        self.work_dir = work_dir
        self.session_dir = session_dir
        self.context_file = context_file
        self.session_file = session_file
        self.tools = config.allowed_tools if tools is None else tools
        self.model = model or config.model
        self.prompt_file = prompt_file
        self.track_partial = track_partial
        self.activity = Activity()
        self.model_info: dict = {}  # get_state's model, as Aelix last reported it
        self.process: asyncio.subprocess.Process | None = None
        self.stray_lines = 0
        self.oversized_lines = 0
        self._tasks: list[asyncio.Task] = []
        self._pending: dict[str, asyncio.Future] = {}
        self._write_lock = asyncio.Lock()
        self._run_lock = asyncio.Lock()
        self._close_lock = asyncio.Lock()
        self._close_task: asyncio.Task | None = None
        self._policy_ready = asyncio.Event()
        self._wake = asyncio.Event()
        self._nonce = uuid.uuid4().hex
        self._failure: RpcError | None = None
        self._reader_done = False
        self._closed = False
        # Per-prompt run tracking, fed by the stdout reader.
        self._started = self._ended = 0
        self._open = False
        self._verdict: tuple[str | None, str] | None = None
        self._busy = False  # a prompt was accepted and Aelix may still be running it
        self._settling = False  # an answer was returned while Aelix may still be busy
        # Steering: messages injected into the running prompt, and answers sealed when Aelix
        # took one in (see Turn). Request index 0 is the prompt, n is _steers[n - 1].
        self._steers: list[_Steer] = []
        self._steering = False  # steer() may inject into the running prompt
        self._owner = 0  # the request the answer in progress belongs to
        self._sealed: list[tuple[int, str]] = []
        self._steer_calls: set[asyncio.Future] = set()
        self._partial_line: bytearray | None = None
        self._expect_echo = False  # the next user message is the submitted prompt itself
        # abort_run() counts up; a turn notes the count when it is called, so an abort that
        # arrives while the turn still waits for the run lock is not lost.
        self._abort_epoch = self._turn_epoch = 0
        self._stderr = bytearray()
        self._stderr_cut = self._stderr_done = False

    @property
    def alive(self) -> bool:
        return (self.process is not None and self.process.returncode is None
                and not self._closed and self._failure is None)

    async def idle(self) -> bool:
        """Whether stopping this child interrupts nothing: no prompt in flight and no
        compaction still running after an answer. A dead child is idle."""
        if not self.alive:
            return True
        if self._run_lock.locked():  # a prompt or a manual compaction
            return False
        if self._settling and not self._busy:
            try:
                state = _data("get_state", await self._call("get_state", {}, self.probe_timeout))
            except RpcError:
                return not self.alive
            self._settling = state.get("isStreaming") is True
        return not (self._busy or self._settling)

    def argv(self) -> list[str]:
        args = [*self.config.command, "--mode", "rpc", "--no-agents", "--no-skills",
                "--no-context-files", "--no-extensions", "--no-approve",
                "--session-dir", str(self.session_dir)]
        if self.config.offline:
            args.append("--offline")
        if self.model:
            args.extend(["--model", self.model])
        if self.session_file and self.session_file.is_file():
            args.extend(["--session", str(self.session_file)])
        if self.prompt_file is not None:
            args.extend(["--append-system-prompt-file", str(self.prompt_file)])
        if not self.tools:
            args.append("--no-tools")
        else:
            args.extend(["--tools", ",".join(self.tools),
                         "-e", str(Path(__file__).with_name("policy.py"))])
            for extension in self.config.extensions:
                args.extend(["-e", extension if os.path.isabs(extension) else self._module_shim(extension)])
        return args

    def _module_shim(self, reference: str) -> str:
        """A file that imports an installed extension module by name.

        Aelix resolves a bare module name against its working directory first, where tools
        can write; a .py path is always loaded as that file, so the name never reaches it."""
        module, _, attribute = reference.partition(":")
        directory = self.config.state_dir / "extension-modules"
        private_directory(directory)
        digest = hashlib.sha256(reference.encode()).hexdigest()[:12]
        path = directory / f"{re.sub(r'[^A-Za-z0-9_]', '_', module)[:60]}_{digest}.py"
        source = _SHIM.format(reference=reference, module=module, attribute=attribute or "setup")
        try:
            current = path.read_text(encoding="utf-8")
        except OSError:
            current = None
        if current != source:
            write_text(path, source)
        return str(path)

    def _environment(self) -> dict[str, str]:
        env = dict(os.environ)
        # The model's shell/tool environment must never inherit the gateway's credentials;
        # an inherited delegation depth would make Aelix block every domain tool.
        for name in (self.config.token_env, "MATTERMOST_TOKEN", self.config.slash_token_env,
                     "MATTERMOST_SLASH_TOKEN", "AELIX_SUBAGENT_DEPTH"):
            env.pop(name, None)
        # Ambient MCP servers (agent_dir/mcp.json, a work-dir .aelix/mcp.json or an
        # inherited $AELIX_MCP_CONFIG) start only when aelix.mcp_config names a file.
        mcp = getattr(self.config, "mcp_config", None)
        env["AELIX_MCP_CONFIG"] = str(Path(mcp).resolve()) if mcp else os.devnull
        env["AELIX_MATTERMOST_CONTEXT_FILE"] = str(self.context_file)
        env["AELIX_MATTERMOST_ALLOWED_TOOLS"] = json.dumps(list(self.tools))
        env["AELIX_MATTERMOST_MAX_TOOL_CALLS"] = str(self.config.max_tool_calls)
        env["AELIX_MATTERMOST_POLICY_NONCE"] = self._nonce
        return env

    def _startup_timeout(self) -> float:
        # Never shorter than an ordinary RPC round trip; 60 s when not configured.
        value = getattr(self.config, "startup_timeout", None) or 60.0
        return max(float(value), float(self.config.rpc_timeout))

    async def start(self) -> dict:
        options: dict[str, Any] = {}
        if os.name == "posix":
            options["start_new_session"] = True
        elif os.name == "nt":
            options["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP
        try:
            # A concurrent close must wait for ownership of the spawned child.
            async with self._close_lock:
                if self._closed or self._close_task is not None:
                    raise RpcError("Aelix RPC process was stopped")
                self.process = await asyncio.create_subprocess_exec(
                    *self.argv(), cwd=self.work_dir, env=self._environment(),
                    stdin=asyncio.subprocess.PIPE, stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE, **options,
                )
                self._tasks = [asyncio.create_task(self._read_stdout()),
                               asyncio.create_task(self._read_stderr()),
                               asyncio.create_task(self._watch_exit())]
            # A cold start can take far longer than one ordinary RPC round trip.
            deadline = asyncio.get_running_loop().time() + self._startup_timeout()
            try:
                async with asyncio.timeout_at(deadline):
                    state = _data("get_state", await self._call("get_state", {}, None))
            except TimeoutError as exc:
                raise RpcTimeout("Aelix did not answer get_state within startup_timeout") from exc
            if self.tools:
                try:
                    async with asyncio.timeout_at(deadline):
                        await self._policy_acknowledged()
                except TimeoutError as exc:
                    raise RpcError("Aelix did not acknowledge the required tool policy") from exc
            self._remember_session(state)
            return state
        except BaseException:
            await self.close()
            raise

    @property
    def vision(self) -> bool:
        """Whether the current model reads images (Aelix replaces them with a note otherwise)."""
        model = self.model_info
        return isinstance(model.get("input"), list) and "image" in model["input"]

    @property
    def model_name(self) -> str:
        model = self.model_info
        provider, name = model.get("provider"), model.get("id")
        if isinstance(provider, str) and isinstance(name, str) and provider and name:
            return f"{provider}/{name}"
        return ""

    async def state(self) -> dict:
        state = await self.request("get_state")
        self._remember_session(state)
        return state

    async def stats(self) -> dict:
        return await self.request("get_session_stats")

    async def available_models(self) -> list[dict]:
        data = await self.request("get_available_models")
        models = data.get("models")
        return [x for x in models if isinstance(x, dict)] if isinstance(models, list) else []

    async def set_model(self, provider: str, model_id: str) -> dict:
        data = await self.request("set_model", provider=provider, modelId=model_id)
        self.model_info = data
        return data

    async def compact(self) -> dict:
        """Compact the conversation now; only while no prompt is running."""
        async with self._run_lock:
            if self._settling:
                await self._wait_idle()
            response = await self._call("compact", {}, self.config.run_timeout)
            if response.get("success") is not True and "Nothing to compact" in str(response.get("error", "")):
                raise NothingToCompact("Nothing to compact")
            return _data("compact", response)

    def _remember_session(self, state: dict) -> None:
        model = state.get("model")
        if isinstance(model, dict):
            self.model_info = model
        filename = state.get("sessionFile")
        if not isinstance(filename, str) or not filename:
            raise RpcError("Aelix did not provide a persistent sessionFile")
        path = Path(filename).resolve()
        if not path.is_relative_to(self.session_dir.resolve()):
            raise RpcError("Aelix session file is outside its assigned session directory")
        self.session_file = path

    async def request(self, command: str, **payload: Any) -> dict:
        return _data(command, await self._call(command, payload, self.config.rpc_timeout))

    async def _call(self, command: str, payload: dict[str, Any], timeout: float | None,
                    force: bool = False) -> dict:
        """Send one command and return its raw response; `force` serves close()."""
        process = self.process
        if (process is None or process.stdin is None or process.returncode is not None
                or self._reader_done or not (force or self.alive)):
            raise RpcError("Aelix RPC process is unavailable")
        identifier = uuid.uuid4().hex
        future = asyncio.get_running_loop().create_future()
        self._pending[identifier] = future
        packet = {"id": identifier, "type": command, **payload}
        try:
            async with self._write_lock:
                process.stdin.write((json.dumps(packet, ensure_ascii=False) + "\n").encode())
                await process.stdin.drain()
            async with asyncio.timeout(timeout):
                return await future
        except TimeoutError as exc:
            raise RpcTimeout(f"RPC command timed out: {command}") from exc
        except (BrokenPipeError, ConnectionError) as exc:
            raise RpcError("Aelix RPC pipe closed") from exc
        finally:
            self._pending.pop(identifier, None)

    async def run(self, text: str) -> str:
        """The final answer to a prompt (steered answers aside)."""
        return (await self.turn(text)).text

    async def turn(self, text: str, images: list[dict] | None = None) -> Turn:
        """Run one prompt, with any messages steer() injects into it, to its answers.

        On failure, the answers Aelix completed before it stay readable as `answers`."""
        epoch = self._abort_epoch
        async with self._run_lock:
            self._turn_epoch = epoch
            self._steers, self._sealed, self._owner = [], [], 0
            self._partial_line = None
            self.activity = Activity()
            try:
                async with asyncio.timeout(self.config.run_timeout):
                    await self._submit(text, images)
                    await self._collect()
                    while stranded := await self._stranded():
                        # Aelix had finished its loop when these arrived: run them as one more prompt.
                        for steer in stranded:
                            steer.state = "taken"
                        self._owner = next(i for i, x in enumerate(self._steers, 1) if x is stranded[-1])
                        images = [image for x in stranded for image in (x.images or [])] or None
                        self._partial_line, self.activity.partial = None, ""
                        await self._submit("\n\n".join(x.text for x in stranded), images)
                        await self._collect()
                    if self._aborted:  # stopped while it finished: its answers still go out
                        raise RpcRunFailed("The run was stopped")
                    state = await self.request("get_state")
                    self._remember_session(state)
            except RpcRunFailed as exc:
                self._busy = self._steering = False
                exc.answers = self.answers
                await self._discard_steers()
                raise
            except TimeoutError as exc:
                self._steering = False
                await self.close()
                raise RpcTimeout("The Aelix run exceeded its time limit") from exc
            except BaseException:
                # Protocol failure, child death or cancellation: abort the run, stop the child.
                self._steering = False
                await self.close()
                raise
            self._busy = False
            # Threshold compaction runs after the final agent_end; the next prompt waits.
            self._settling = state.get("isStreaming") is True
            return Turn(self.answers)

    @property
    def _aborted(self) -> bool:
        return self._abort_epoch != self._turn_epoch

    @property
    def answers(self) -> list[tuple[int, str]]:
        """The answers of the current (or last) turn completed so far, length-limited."""
        return self._limited(self._sealed)

    async def _collect(self) -> None:
        """Steerable while Aelix answers the prompt just submitted; keep its answer."""
        self._steering = not self._aborted
        try:
            answer = await self._await_answer()
        finally:
            self._steering = False
        self._sealed.append((self._owner, answer))

    def _limited(self, answers: list[tuple[int, str]]) -> list[tuple[int, str]]:
        limit = self.config.max_output_chars
        return [(owner, text if len(text) <= limit else text[:limit] + "\n\n… 응답 길이 제한으로 일부를 생략했습니다.")
                for owner, text in answers]

    @property
    def steerable(self) -> bool:
        """Whether steer() can inject a message into the prompt that is running now."""
        return self._steering and not self._aborted and self.alive

    @property
    def next_steer_index(self) -> int:
        """The request index the next steer() call gets, if it is steerable."""
        return len(self._steers) + 1

    async def steer(self, text: str, images: list[dict] | None = None) -> int | None:
        """Inject a message into the running prompt; returns its request index, or None
        when no prompt is running (the caller then queues it as a prompt of its own)."""
        if not self.steerable:
            return None
        steer = _Steer(text, images)
        self._steers.append(steer)  # before sending: Aelix may take it in before it answers
        index = len(self._steers)
        payload: dict[str, Any] = {"message": text}
        if images:
            payload["images"] = images
        call = asyncio.ensure_future(self._call("steer", payload, self.config.rpc_timeout))
        self._steer_calls.add(call)
        call.add_done_callback(self._steer_calls.discard)
        try:
            response = await asyncio.shield(call)
        except RpcError:
            response = {}
        if response.get("success") is not True:
            if steer.state == "sending":
                steer.state = "failed"  # perhaps queued anyway: _stranded() clears Aelix's queue
            return None if steer.state == "failed" else index
        if steer.state == "sending":
            steer.state = "queued"
        return index

    async def _stranded(self) -> list[_Steer]:
        """Steered messages Aelix queued after its loop had ended, removed from its queue.

        A message Aelix took in (or changed with an input hook, so it never matched) is not
        stranded; one still in Aelix's queue would otherwise be answered after the next
        prompt in place of it. A steer whose RPC failed may still have been queued: the
        caller runs it as a request of its own, so it is cleared here but not returned."""
        if self._steer_calls:
            await asyncio.gather(*tuple(self._steer_calls), return_exceptions=True)
        if not self._steers:
            return []
        await self._wait_idle(abortable=True)  # a compaction after agent_end keeps them queued
        state = await self.request("get_state")
        waiting = [x for x in self._steers if x.state == "queued"]
        if state.get("pendingMessageCount"):
            await self.request("abort")  # clears Aelix's steering queue
            return waiting
        if self._aborted:
            return []  # the stop's abort cleared them: they were never answered
        for steer in waiting:
            steer.state = "taken"  # consumed without a match: merged into the answer
        return []

    async def _discard_steers(self) -> None:
        """After a failed run: no steered message may stay queued for the next prompt."""
        if not self._steers and not self._steer_calls:
            return
        try:
            if self._steer_calls:
                await asyncio.gather(*tuple(self._steer_calls), return_exceptions=True)
            state = await self.request("get_state")
            if state.get("pendingMessageCount"):
                await self.request("abort")
        except RpcError:
            await self.close()  # a child that cannot be cleared must not answer the next prompt

    async def abort_run(self) -> None:
        """Stop the running prompt but keep the child: its turn ends with "aborted". A
        prompt not yet submitted is never sent."""
        self._abort_epoch += 1
        self._steering = False
        if self._busy:
            await self.request("abort")

    async def _submit(self, text: str, images: list[dict] | None = None) -> None:
        """Send the prompt once Aelix is idle; wait and resend after a busy rejection."""
        payload: dict[str, Any] = {"message": text}
        if images:
            payload["images"] = images
        while True:
            if self._settling:
                await self._wait_idle(abortable=True)
            if self._aborted:
                raise RpcRunFailed("The run was stopped before it started")
            self._started = self._ended = 0
            self._open, self._verdict, self._busy = False, None, True
            self._expect_echo = True  # the prompt's own user message is not a steered one
            response = await self._call("prompt", payload, self.config.rpc_timeout)
            if response.get("success") is True:
                if self._aborted:  # an abort that raced the prompt may have reached Aelix first
                    await self.request("abort")
                return
            self._busy = False
            if "is busy" not in str(response.get("error", "")):
                raise RpcRunFailed("Aelix rejected the prompt")
            self._settling = True

    async def _wait_idle(self, abortable: bool = False) -> None:
        """Wait until Aelix is idle (a compaction after an answer ends); with `abortable`,
        abort_run() ends the wait, so a stopped request never kills the child to get out."""
        while (await self.request("get_state")).get("isStreaming") is True:
            if abortable and self._aborted:
                raise RpcRunFailed("The run was stopped before it started")
            await asyncio.sleep(self.poll_interval)
        self._settling = False

    async def _await_answer(self) -> str:
        """Follow the runs of an accepted prompt (retries, overflow recovery) to a verdict."""
        loop = asyncio.get_running_loop()
        grace = loop.time() + self.start_grace
        while True:
            self._wake.clear()
            self._raise_failure()
            finished = self._ended > 0 and not self._open
            if finished and (answer := self._answer()) is not None:
                return answer
            if self._open or (not finished and loop.time() < grace):
                await self._pause(self.poll_interval)
                continue
            # A failed run may still be retried or recovered, and a prompt may still be
            # starting. Once Aelix reports idle, every event of this prompt has arrived.
            if (await self.request("get_state")).get("isStreaming") is not True:
                if not self._open and self._ended > 0 and (answer := self._answer()) is not None:
                    return answer
                raise self._verdict_error()
            await self._pause(self.poll_interval)

    def _answer(self) -> str | None:
        if self._verdict is None:
            return None
        reason, text = self._verdict
        return text.strip() if reason not in _FAILED and text.strip() else None

    def _verdict_error(self) -> RpcRunFailed:
        if self._open or not self._ended:
            return RpcRunFailed("Aelix went idle without finishing the run" if self._started
                              else "Aelix accepted the prompt but did not start a run")
        if self._verdict is None:
            return RpcRunFailed("The Aelix run ended without a readable assistant message")
        if self._verdict[0] in _FAILED:
            return RpcRunFailed(f"The Aelix run ended with stop reason '{self._verdict[0]}'")
        return RpcRunFailed("Aelix returned an empty final answer")

    async def _pause(self, seconds: float) -> None:
        """Sleep until the reader reports progress or `seconds` pass."""
        with contextlib.suppress(TimeoutError):
            async with asyncio.timeout(seconds):
                await self._wake.wait()

    def _raise_failure(self) -> None:
        if self._failure is not None:
            raise RpcError(str(self._failure))

    async def _policy_acknowledged(self) -> None:
        while True:
            self._wake.clear()
            if self._policy_ready.is_set():
                return
            self._raise_failure()
            await self._pause(self.poll_interval)

    async def _read_stdout(self) -> None:
        assert self.process is not None and self.process.stdout is not None
        frames = _Lines(self.max_line)
        try:
            # read(), never readline(): no separator limit can wedge or kill the stream.
            while chunk := await self.process.stdout.read(_CHUNK):
                for line, head, tail in frames.feed(chunk):
                    if line is None:
                        self.oversized_lines += 1
                        log.warning("Dropped an Aelix RPC line over %d bytes", self.max_line)
                    self._route(line, head, tail)
        except OSError:
            pass
        finally:
            self._reader_done = True
            self._fail(RpcError("Aelix RPC output ended"))

    def _route(self, line: bytearray | None, head: bytes, tail: bytes) -> None:
        """Dispatch one stdout line; `line` is None when it exceeded max_line."""
        if line is not None and len(line) <= _EDGE and not head.strip():
            return
        if _RESPONSE.match(head):
            self._on_response(_load(line), head)
            return
        kind = _group(_EVENT, tail[-256:])
        if kind is None:  # not the dataclass layout: only a full parse can tell
            packet = _load(line)
            kind = packet.get("type") if packet is not None else None
            if kind == "response":
                self._on_response(packet, head)
            elif isinstance(kind, str):
                self._on_event(kind, packet)
            elif line is not None:  # oversized lines were already counted
                self.stray_lines += 1
                if self.stray_lines == 1:
                    log.warning("Ignored non-JSON Aelix stdout; extensions must print to stderr")
            return
        if kind == "message_update":
            self._on_update(line, tail)
            return
        # Assistant messages matter; user messages only while a steered one may arrive.
        # agent_end (which repeats the whole run) is never parsed.
        role = _group(_ROLE, tail[-256:]) if kind == "message_end" else None
        if role == "user":
            if self._expect_echo:
                self._expect_echo = False  # the prompt itself
                return
            if not self._steers or line is None:
                return  # no steered message to match, or one too large to read
        wanted = kind in ("turn_end", "tool_execution_start") or (
            kind == "message_end" and role in (None, "assistant", "user"))
        self._on_event(kind, (_load(line) or {}) if wanted else None)

    def _on_update(self, line: bytearray | None, tail: bytes) -> None:
        """A streaming delta: only its kind is read now; the text when partial() asks."""
        delta = _group(_DELTA, tail[-256:]) or ""
        if delta.startswith("thinking"):
            self.activity.phase = "thinking"
        elif delta.startswith("text"):
            self.activity.phase = "writing"
            if self.track_partial and line is not None:
                self._partial_line = line

    def partial(self) -> str:
        """The answer text streamed so far in the current turn ("" when not tracked)."""
        line, self._partial_line = self._partial_line, None
        if line is not None:
            packet = _load(line) or {}
            event = packet.get("assistant_message_event")
            partial = event.get("partial") if isinstance(event, dict) else None
            if isinstance(partial, dict):
                self.activity.partial = _outcome(partial)[1]
        return self.activity.partial

    def _took_in(self, message: dict) -> None:
        """A user message started a turn: the prompt itself, or a steered message."""
        content = message.get("content")
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            text = "".join(x["text"] for x in content if isinstance(x, dict) and x.get("type") == "text"
                           and isinstance(x.get("text"), str))
        else:
            return
        if self._expect_echo:
            self._expect_echo = False  # the prompt itself
            return
        waiting = [i for i, x in enumerate(self._steers, 1) if x.state in ("sending", "queued")]
        index = next((i for i in waiting if self._steers[i - 1].text == text), None)
        if index is None:
            return
        # Aelix takes steered messages in order, so earlier unmatched ones were changed by an
        # input hook and merged; the answer completed so far belongs to the previous request.
        for i in waiting:
            if i <= index:
                self._steers[i - 1].state = "taken"
        if self._verdict is not None:
            reason, answer = self._verdict
            if reason not in _FAILED and reason not in _TOOL_USE and answer.strip():
                self._sealed.append((self._owner, answer.strip()))
        self._verdict, self._owner = None, index
        self.activity.partial, self._partial_line = "", None

    def _on_response(self, packet: dict | None, head: bytes) -> None:
        identifier = packet.get("id") if packet is not None else _group(_RESPONSE_ID, head)
        future = self._pending.get(identifier) if isinstance(identifier, str) else None
        if future is None or future.done():
            return
        if packet is None:
            future.set_exception(RpcError("Aelix sent a malformed or oversized RPC response"))
        else:
            future.set_result(packet)

    def _on_event(self, kind: str, packet: dict | None) -> None:
        activity = self.activity
        if kind == "agent_start":
            self._started += 1
            self._open, self._verdict = True, None
            activity.phase = "thinking"
        elif kind == "agent_end":
            self._ended += 1
            self._open = False
        elif kind in ("message_end", "turn_end") and packet is not None:
            # turn_end carries the final (hook-replaced) message; message_end the original.
            message = packet.get("message")
            if not isinstance(message, dict):
                self._verdict = None  # oversized or malformed: this turn's outcome is unknown
            elif message.get("role") == "assistant":
                self._verdict = _outcome(message)
            elif message.get("role") == "user" and kind == "message_end":
                self._took_in(message)
        elif kind in _PROGRESS:
            if kind == "tool_execution_start":
                name = packet.get("tool_name") if packet else None
                activity.phase, activity.tool = "tool", name if isinstance(name, str) else ""
                activity.tools_used += 1
            elif kind == "auto_retry_start":
                activity.phase = "retrying"
            elif kind == "compaction_start":
                activity.phase = "compacting"
            else:
                activity.phase = "writing" if kind == "message_update" else "thinking"
            return
        else:
            return
        self._wake.set()

    async def _read_stderr(self) -> None:
        assert self.process is not None and self.process.stderr is not None
        expected = f"aelix-mattermost-policy-ready:{self._nonce}".encode()
        partial = b""
        try:
            while chunk := await self.process.stderr.read(_CHUNK):
                self._stderr += chunk
                if len(self._stderr) > _STDERR_KEEP:
                    del self._stderr[:-_STDERR_KEEP]
                    self._stderr_cut = True
                *lines, partial = (partial + chunk).split(b"\n")
                if any(line.strip() == expected for line in lines):
                    self._policy_ready.set()
                    self._wake.set()
                if len(partial) > len(expected) + 64:
                    partial = b"\0"  # an overlong line can never be the marker
        except OSError:
            pass
        finally:
            self._stderr_done = True

    def stderr_tail(self) -> str:
        """Recent Aelix stderr: complete lines only, redacted, at most 8 KiB."""
        data = bytes(self._stderr)
        if self._stderr_cut:
            data = data.partition(b"\n")[2]
        if not self._stderr_done:
            data = data[:data.rfind(b"\n") + 1]
        text = _redact(data.decode("utf-8", "replace"), self.config.token).strip()
        return text.encode()[-_STDERR_TAIL:].decode("utf-8", "ignore")

    async def _watch_exit(self) -> None:
        assert self.process is not None
        while self.process.returncode is None:  # not wait(): see _exited()
            await asyncio.sleep(0.1)
        # Let already buffered final stdout packets drain before reporting death.
        await asyncio.wait(self._tasks[:1], timeout=0.5)
        self._fail(RpcError("Aelix RPC process exited"))

    def _fail(self, error: RpcError) -> None:
        if self._failure is None:
            self._failure = error
        for future in tuple(self._pending.values()):
            if not future.done():
                future.set_exception(RpcError(str(error)))
        self._wake.set()

    async def close(self) -> None:
        async with self._close_lock:
            if self._close_task is None:
                self._close_task = asyncio.create_task(self._close())
            cleanup = self._close_task
        # Repeated cancellation of a caller must not abandon process-tree cleanup.
        await asyncio.shield(cleanup)

    async def _close(self) -> None:
        active = self._busy or self._settling
        self._closed = True
        self._fail(RpcError("Aelix RPC process was stopped"))
        process = self.process
        if process is not None:
            if active and process.returncode is None and not self._reader_done:
                await self._abort()
            await self._stop(process)
        current = asyncio.current_task()
        tasks = [task for task in self._tasks if task is not current]
        for task in tasks:
            task.cancel()
        await asyncio.gather(*tasks, return_exceptions=True)

    async def _abort(self) -> None:
        """Let Aelix end the run and its tool process trees, which outlive killpg."""
        with contextlib.suppress(RpcError, OSError, TimeoutError):
            async with asyncio.timeout(self.abort_grace):
                await self._call("abort", {}, None, force=True)
                while True:
                    data = (await self._call("get_state", {}, None, force=True)).get("data")
                    if not isinstance(data, dict) or data.get("isStreaming") is not True:
                        return
                    await asyncio.sleep(0.05)

    async def _stop(self, process: asyncio.subprocess.Process) -> None:
        """Close stdin, ask the group to exit, then SIGKILL whatever is left."""
        if process.stdin is not None:
            with contextlib.suppress(OSError, RuntimeError):
                process.stdin.close()
        # POSIX signals go by group id: Popen.terminate()/kill() may reap the child
        # behind asyncio's watcher.
        if os.name == "posix":
            _killpg(process.pid, signal.SIGTERM)
        elif process.returncode is None:
            with contextlib.suppress(OSError, ValueError):
                process.send_signal(getattr(signal, "CTRL_BREAK_EVENT", signal.SIGTERM))
        if not await _exited(process, self.term_grace):
            if os.name == "posix":
                _killpg(process.pid, signal.SIGKILL)
            else:
                if os.name == "nt":
                    killer = await asyncio.create_subprocess_exec(
                        "taskkill", "/PID", str(process.pid), "/T", "/F",
                        stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL,
                    )
                    await killer.wait()
                with contextlib.suppress(ProcessLookupError, OSError):
                    process.kill()
            await _exited(process, 5)
        if os.name == "posix":
            # Also end same-group grandchildren when the parent exits cooperatively.
            _killpg(process.pid, signal.SIGKILL)
        # Release our pipe ends even if a descendant in another session holds them.
        transport = getattr(process, "_transport", None)
        if transport is not None:
            with contextlib.suppress(Exception):
                transport.close()
